default_provider = "age"

[providers.age]
type = "age"
recipients = ["age1j3da7kya9xsjaw7gdecrckk5a6qjyq5gwv3ye30uqjrmmkaq5c6qpyqddh"]

[secrets]
SONAR_TOKEN= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RytGQlR0TnNlNXhkb2NoMW01Y3Y5K013dlg1YzJiWEUvOXVqeHVKb0JrCkJKdC83UENsemVZZTRGMHUrZWk3Z1hCNHUxQlhzQUxpR1hueUg0VTB6UmcKLT4gMyxvSC1ncmVhc2UgblBMbiAmIGVhXgpmanlmZXRSdjIxRDc5V3VFT0dHRHlKWWM3ZHVzaE1JWEYyWDc5aFZTUGM0bVNBelorbXRXVDF2WAotLS0gclZxRGI3aXlMQnFCaHZ4K3Z0NzR2OHpLRm5kZEh1WWJ5UG5vRVNLV2RuUQoZrZ0stEFXVLE7rPoCNKcIGUjVU7SvWasBwXXQT+ssS7Dg0ICCGCbTuTv7OVGvuSakLTJL78Jo17pKHqUc/09mMMMc19A7IdPj/WaW" }
